name: deploy 
on:
  schedule:
    - cron: "* * * * *" #runs every minute

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt 
      - run: python apr.py